version: "3.9"

services:
  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000

  kafka:
    image: confluentinc/cp-kafka:latest
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
    environment:
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1

  parser:
    build:
      context: .
      dockerfile: Dockerfile.parser
    volumes:
      - ./datasets:/datasets
    environment:
      - KAFKA_SERVER=kafka:9092
    depends_on:
      - kafka

  kafka_producer:
    build:
      context: .
      dockerfile: Dockerfile.kafka_producer
    environment:
      - KAFKA_SERVER=kafka:9092
    depends_on:
      - parser

  grafana:
    image: grafana/grafana:latest
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
    volumes:
      - ./grafana/datasources.yaml:/etc/grafana/provisioning/datasources/datasources.yaml
    depends_on:
      - kafka
  loki:
    image: grafana/loki:2.7.3
    ports:
      - "3100:3100"
