FROM python:3.9-slim
WORKDIR /app
COPY requirements.txt requirements.txt
RUN pip install -r requirements.txt
COPY kafka_producer /app/kafka_producer
CMD ["python", "/app/kafka_producer/kafka_producer.py"]
